apiVersion: v1
name: osiris
description: A general purpose, scale-to-zero component for Kubernetes
version: 0.0.1 # This gets automatically overridden by our release process
appVersion: latest # This gets automatically overridden by our release process
home: https://github.com/dailymotion-oss/osiris
sources:
- https://github.com/dailymotion-oss/osiris
